auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_scheduler:
  max_outstanding_requests_per_tenant: 2048

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Минимальные лимиты
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_parallelism: 32
  max_query_series: 5000
  max_query_lookback: 0s
  max_entries_limit_per_query: 5000
  max_query_length: 721h
  cardinality_limit: 100000
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  ingestion_rate_mb: 16
  ingestion_burst_size_mb: 32
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_line_size: 256000
  max_line_size_truncate: true
  allow_structured_metadata: false

# Настройки для парсинга логов
table_manager:
  retention_deletes_enabled: false
  retention_period: 744h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: false

analytics:
  reporting_enabled: false

