name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Тесты и сборка
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Build binary
        run: go build -o bin/api ./cmd/api/

  # Деплой на сервер
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            cd ${{ secrets.PROJECT_PATH || '/opt/labracodabrador' }}
            git pull origin main
            docker-compose -f config/docker-compose.yml down
            docker-compose -f config/docker-compose.yml build api-server
            docker-compose -f config/docker-compose.yml up -d
            echo "✅ Deployment completed successfully!"

